export enum permissions {
	// Product Permissions
	PRODUCT_CREATE = 'PRODUCT_CREATE',
	PRODUCT_READ = 'PRODUCT_READ',
	PRODUCT_UPDATE = 'PRODUCT_UPDATE',
	PRODUCT_DELETE = 'PRODUCT_DELETE',
	PRODUCT_BULK_OPERATIONS = 'PRODUCT_BULK_OPERATIONS',
  
	// Inventory Permissions
	INVENTORY_READ = 'INVENTORY_READ',
	INVENTORY_UPDATE = 'INVENTORY_UPDATE',
	INVENTORY_BULK_UPDATE = 'INVENTORY_BULK_UPDATE',
  
	// Category Permissions
	CATEGORY_CREATE = 'CATEGORY_CREATE',
	CATEGORY_READ = 'CATEGORY_READ',
	CATEGORY_UPDATE = 'CATEGORY_UPDATE',
	CATEGORY_DELETE = 'CATEGORY_DELETE',
  
	// Search Permissions
	PRODUCT_SEARCH = 'PRODUCT_SEARCH',
	ADVANCED_SEARCH = 'ADVANCED_SEARCH',
  
	// Image Permissions
	IMAGE_UPLOAD = 'IMAGE_UPLOAD',
	IMAGE_DELETE = 'IMAGE_DELETE',
  }
  